GET http://localhost:4000/articles/



###

POST http://localhost:4000/articles/
Content-type: application/json
 
 {
    "title": "dfdf", 
    "subtitle": "dfdff", 
    "intro": "dfdfd" 
 }
 



###
DELETE http://localhost:4000/delete/3


###
PATCH http://localhost:4000/articles/3
Content-type: application/json
  
{
     "title": "exampleee"
}