GET http://localhost:4000/ads/



###

POST http://localhost:4000/ads/
Content-type: application/json
 
 {
      "id": "1",
    "title": "puppy", 
    "author": "dfdff", 
    "description": "tehsfdhgnbhfghd",
    "price": 45,
    "createdAt": "",
   "location": "tehsbldsdsd",
   "id_category": 1

 }


###
DELETE http://localhost:4000/delete/1


###
PATCH http://localhost:4000/articles/3
Content-type: application/json
  
{
     "title": "exampleee"
}

###
PUT http://localhost:4000/ads/44
Content-type: application/json
  
{
      "id": "56",
    "title": "dfdf", 
    "author": "dfdff", 
    "description": "tehsfdhgnbhfghd",
    "price": 34,
    "createdAt": "",
   "location": "tehsbldsdsd",
   "id_category": 1

 }